// File generated by hand from google-services.json (com.petitworksapps.japanfuturemap)
// Project: petit-works-apps-9029a（当面はfunvestment1@gmail.comで運用）

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run flutterfire configure to add a web app if needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS向けのFirebase設定が未登録です。Firebase Console '
          '（プロジェクト: petit-works-apps-9029a）で iOS アプリを追加し'
          '（Bundle ID: com.yourwish.japanfuturemap）、'
          'ダウンロードした GoogleService-Info.plist の値をもとに '
          'このファイルに `ios` という名前の FirebaseOptions を追加してください。',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIt1e0hN8K3dl7HN2CoH_h95ztkNrgmg',
    appId: '1:216377882454:android:189037cc74accf69d108f7',
    messagingSenderId: '216377882454',
    projectId: 'petit-works-apps-9029a',
    storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
  );

  // iOS向けアプリをFirebase Consoleに追加後、GoogleService-Info.plistの値で
  // 以下のようなFirebaseOptionsを追加し、上のswitch文からreturn iosに差し替えてください。
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: '...',
  //   appId: '1:216377882454:ios:...',
  //   messagingSenderId: '216377882454',
  //   projectId: 'petit-works-apps-9029a',
  //   storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
  //   iosBundleId: 'com.yourwish.japanfuturemap',
  // );
}
