// File generated by hand from google-services.json (com.petitworksapps.japanfuturemap)
// Project: petit-works-apps-9029a（当面はfunvestment1@gmail.comで運用）

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run flutterfire configure to add a web app if needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIt1e0hN8K3dl7HN2CoH_h95ztkNrgmg',
    appId: '1:216377882454:android:189037cc74accf69d108f7',
    messagingSenderId: '216377882454',
    projectId: 'petit-works-apps-9029a',
    storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
  );

  // 注意: iOS版はAndroid版（petit-works-apps-9029a）とは別のFirebaseプロジェクト
  // （apps2-752cb、他アプリと共用）に接続する構成。ユーザーの明示的な選択により、
  // OS間でFirestoreデータ（投票・コメント・提案等）は共有されない。
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gaFcLxN8iT7xm6JeIM7Iou-efE5g5SM',
    appId: '1:946448575860:ios:0fd631a6510c7fab37d021',
    messagingSenderId: '946448575860',
    projectId: 'apps2-752cb',
    storageBucket: 'apps2-752cb.firebasestorage.app',
    iosBundleId: 'com.yourwish.japanfuturemap',
  );
}
